language: python
python:
  - {{ cookiecutter.python_version }}
  - pypy3
os:
  - linux
git:
  depth: 1
before_install:
  - pip install pip --upgrade
install:
  - make dist
  - pip install dist/{{cookiecutter.package_name}}-*.whl
script:
  - make test
